[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bmdbutils"
version = "0.1.0"
description = "BioModelos database utilities."
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Erika Suarez-Valencia", email = "esuarez@humboldt.org.co" },
  { name = "Jorge Luis Higuita Castro", email = "jhiguita@humboldt.org.co" }
]
requires-python = ">=3.10"
dependencies = [
    "setuptools=67",
    "python>=3.10",
    "click>=8.4",
    "pandas>=1.5",
    "pymongo>=4.0",
    "GDAL>=3.13",
    "geoserver-rest = {git = "https://github.com/PEM-Humboldt/geoserver-rest.git"}",
    "appdirs>=1.4",
    "pycurl>=7.45",
    "sqlalchemy>=1.4",
    "psycopg2>=2.9",
    "jsonschema>=4.23",    
]

[project.scripts]
bmdbutils = "bmdbutils.cli.cli:main"

[tool.black]
line-length = 79
target-version = ["py310"]
include = '\.pyi?$'

[tool.setuptools.packages.find]
include = ["bmdbutils*"]
