[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bmdbutils"
version = "1.0.0"
description = "BioModelos database utilities."
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Erika Suarez-Valencia", email = "esuarez@humboldt.org.co" },
  { name = "Jorge Luis Higuita Castro", email = "jhiguita@humboldt.org.co" }
]
requires-python = ">=3.10"

[project.scripts]
bmdbutils = "bmdbutils.cli.cli:main"

[tool.black]
line-length = 79
target-version = ["py310"]
include = '\.pyi?$'

[tool.setuptools.packages.find]
include = ["bmdbutils*"]